services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${ENV}
    depends_on:
      mariadb:
        condition: service_healthy
    command: sh ./entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
      - temp_data:/app_temp
      - /app/.next

  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Root password
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Database name
      MYSQL_USER: ${MYSQL_USER}                    # Name of the user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Password of the user
    ports:
      - "3306:3306"  # Deflaut listening port for mariadb
    volumes:
      - mariadb_data:/var/lib/mariadb  # Data volume for mariadb that contains database files
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb


volumes:
  mariadb_data:
  temp_data:
