version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - phpmyadmin

  mysql:
    image: mysql:8.1  # Version fixe de MySQL (peut être changée en fonction des besoins)
    container_name: mysql
    restart: always
    env_file:
      - .env  # Fichier contenant les variables d'environnement
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Mot de passe root
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Base de données à créer
      MYSQL_USER: ${MYSQL_USER}                    # Nom de l'utilisateur
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Mot de passe utilisateur
    ports:
      - "3306:3306"  # Port MySQL par défaut
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des données dans un volume

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
