services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      mariadb:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma db pull && npx prisma generate && npm run dev"]

  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    restart: always
    env_file:
      - .env  # Fichier contenant les variables d'environnement
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Mot de passe root
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Base de données à créer
      MYSQL_USER: ${MYSQL_USER}                    # Nom de l'utilisateur
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Mot de passe utilisateur
    ports:
      - "3306:3306"  # Port MySQL par défaut
    volumes:
      - mariadb_data:/var/lib/mariadb  # Persistance des données dans un volume
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql # Fichier SQL d'initialisation
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
